### ISSUE TITLE
percdamp clarification for dummies

### ISSUE THREAD

**Issue by diegomontoya** [fpgaminer/GPTQ-triton#10]
I have no clue, even at a guess, of what percdamp does. @fpgaminer  Can you give a short explanation at how this influence quantizing quality in a sentence or two, if possible,  so that a dummy/newbie can at least know if it's worth it to to tune it  (up or down) the value for testing? Thanks.

```
--percdamp: Percent of the average Hessian diagonal to use for dampening.
```

https://github.com/fpgaminer/GPTQ-triton/blob/3daf413123cd55c600966492775f717eb3ac01e0/gptq.py#L87

**Comment by qwopqwop200** [comment]
Step 3: Cholesky Reformulation. The final technical issue we have to address is given by numeri- cal inaccuracies, which can become a major problem at the scale of existing models, especially when combined with the block updates discussed in the previous step. Specifically, it can occur that the matrix H−1 F becomes indefinite, which we notice can cause the algorithm to aggressively update the remaining weights in incorrect directions, resulting in an arbitrarily-bad quantization of the corre- sponding layer. In practice, we observed that the probability of this happening increases with model size: concretely, it almost certainly occurs for at least a few layers on models that are larger than a few billion parameters. The main issue appears to be the repeated applications of Equation (5), which accumulate various numerical errors, especially through the additional matrix inversion.

For smaller models, applying dampening, that is adding a small constant λ(precdamp) (we always choose 1% of the average diagonal value) to the diagonal elements of H appears to be sufficient to avoid numerical issues. However, larger models require a more robust and general approach.

ref: GPTQ paper 5page
