### ISSUE TITLE
Does this support non -1 groupsize?

### ISSUE THREAD

**Issue by vedantroy** [fpgaminer/GPTQ-triton#13]
The README has the following line:
> NOTE: The Triton kernel is currently only implemented for 4-bits and groupsize -1.

At the same time, I notice that there are results for GPTQ-triton using groupsize 128.
Also a few huggingface repositories seem to indicate this repository is compatible with groupsize 128: https://huggingface.co/Neko-Institute-of-Science/LLaMA-13B-4bit-128g/commit/e40634713b45acacb9282f30995495612d8d95b6

Am I missing something?

**Comment by fpgaminer** [comment]
Good catch, thank you.  I hadn't updated that note after adding support for groupsize.
