### ISSUE TITLE
Get C++ when exception when trying to load model

### ISSUE THREAD

**Issue by vedantroy** [fpgaminer/GPTQ-triton#14]
I'm trying to load the 13B quantized model (which I quantized using the script in this repository). But I get the following error:
```
Loading model ...
QuantLinear Warmup: Found 3 unique KN values.
FusedMLP Warmup: Found 1 unique K values.
Warming up autotune cache ...
  0%|                                                                                     | 0/12 [00:00<?, ?it/s]
python3: /project/lib/Analysis/Allocation.cpp:42: std::pair<llvm::SmallVector<unsigned int>, llvm::SmallVector<unsigned int> > mlir::triton::getCvtOrder(const mlir::Attribute&, const mlir::Attribute&): Assertion `!(srcMmaLayout && dstMmaLayout) && "Unexpected mma -> mma layout conversion"' failed.
./generate.bash: line 2:  3996 Aborted                 (core dumped)
```

**Comment by fpgaminer** [comment]
This seems to be a bug in Triton (https://github.com/openai/triton/issues/1298).  Do you have Triton installed at HEAD or 2.0.0?

**Comment by vedantroy** [comment]
> This seems to be a bug in Triton ([openai/triton#1298](https://github.com/openai/triton/issues/1298)). Do you have Triton installed at HEAD or 2.0.0?

I can check. Which version should I have it installed as?

**Comment by vedantroy** [comment]
```
pip list | grep triton
```
gives
```
triton                   2.0.0
```

**Comment by fpgaminer** [comment]
Hmm, I guess try HEAD to see if they've fixed it.  Otherwise, please let me know what GPU you're testing on so I can try to reproduce.

**Comment by vedantroy** [comment]
Works with triton 2.1.0
