### ISSUE TITLE
Getting "CUDA error: an illegal memory access was encountered" with model.generate

### ISSUE THREAD

**Issue by apenugon** [fpgaminer/GPTQ-triton#3]
Hi, thanks for making this! Definitely a lot faster. I'd like to use it with generate() but getting that error in the title. The model works fine just calling it like in ppl.py, but calling the huggingface generate function causes issues. Any idea what's going on?

Below is how I'm calling generate.

```
model.generate(
        **input_tokens,
        do_sample=False,
        min_length=0,
        max_length=newlen,
        temperature=0.6,
        top_p=0.6,
        use_cache=True,
        repetition_penalty=1.1
        ).cpu()
```

**Comment by fpgaminer** [comment]
I haven't tried `generate` yet. I'll have to take a look.  Maybe try disabling `use_cache`?

**Comment by apenugon** [comment]
I tried that, but then it just takes forever - waited for like 30 seconds with a context length of 100 before terminating, GPU was running at max according to nvtop though

**Comment by fpgaminer** [comment]
Actually, now that I think about it I think the kernel isn't set up to handle context lengths that aren't divisible by the block size.  Oops!  I just finished writing and testing the kernel last night, so forgive the bug.  Let me get that patched up.  Hopefully later today.

**Comment by fpgaminer** [comment]
I pushed an update that should fix the issue for you. Please let me know.  On my system generate works correctly now.

**Comment by apenugon** [comment]
It works! This is great, thanks for the speedy fix.
