### ISSUE TITLE
Testing triton on 30b model vs quant_cuda

### ISSUE THREAD

**Issue by diegomontoya** [fpgaminer/GPTQ-triton#4]
I am actually seeing a ~3x slow down on a medium sized input/output. 60s on triton (nightly) vs 20s (latest qptq-llama cuda branch). About ~240 input tokens and output is the same amount. 

Not sure if I am doing something horribly wrong here as it doesn't match or get close to the expected values.

**Comment by fpgaminer** [comment]
Thank you for the report.  What's the speed like on larger contexts?  GPU?  Measurement method?

**Comment by diegomontoya** [comment]
Closing this issue since code base has changed since last report.
